name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 12.x
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 12.x
      - run: |
          npm install
      - run: |
          npm run all
